### PR TITLE
[new] clean up code in modal_aero_convproc.F90 and aero_model.F90

### PR DESCRIPTION
**Pull request by tangshuaiqi**
solve a merge conflict and create a new PR. the old PR will be closed.

clean up code in modal_aero_convproc.F90 and related part in aero_model.F90

code related to following variables are cleaned:
idiag_aa
idiag_gg
idiag_in
itmpa
convproc_method_activate
rain_evap_to_coarse_aero
mam_prevap_resusp_optaa
method_reduce_actfrac
ipass_calc_updraft
lat_deg
lon_deg

### CODE REVIEW

**Review by singhbalwinder — APPROVED** [review]
Looks great! Thanks @tangshuaiqi !

**Review by jeff-cohere — APPROVED** [review]
Great! Thanks for the C++ porting comments.

The only question I would pose (and the answer is up for discussion) is how much attention we should pay to code indentation in these refactoring PRs.

**Comment by tangshuaiqi** [comment]
@jeff-cohere good question! and some other code consistency issues (like end if and endif) as well. It may need a separate PR specifically addressing with these issues. Maybe after refactoring the files, as refactoring process will rewrite a large portion of the code.

**Review by mingxuanwupnnl — APPROVED** [review]

**Review by brigaudet — APPROVED** [review]

**Comment by singhbalwinder** [comment]
All tests passed (tests were run by @tangshuaiqi )
```
$ ./cs.status.comp_testall_clean_modal_aero_convproc_mam4_org_v2_baselines -s
comp_testall_clean_modal_aero_convproc_mam4_org_v2_baselines: 5 tests
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
```
Merging this branch.

**Pull request merged**
