### PR TITLE
yaml / python data files for tropopause_cpp and _hybridstobie

### PR DESCRIPTION
**Pull request by brigaudet**
Create yaml / python data files for tropopause_cpp and tropopause_hybridstobie subroutines within tropopause.F90.
Data are output at all vertical levels for a particular column, because output level is dependent on data at multiple vertical levels.

### CODE REVIEW

**Review by tangshuaiqi — APPROVED** [review]
It looks good to me.

**Review by jeff-cohere — APPROVED** [review]
Thanks for the data files!

**Review by singhbalwinder — APPROVED** [review]
Thanks @brigaudet !

**Comment by brigaudet** [comment]
image

All longer tests passed, will go ahead and commit.

**Pull request merged**
