### PR TITLE
refactor subroutine modal_size_parameters

### PR DESCRIPTION
**Pull request by tangshuaiqi**
some small simplifications and cleanups.

### CODE REVIEW

**Review by brigaudet — APPROVED** [review]
Looks good!

**Review by singhbalwinder — APPROVED** [review]
Looks good! Thanks, @tangshuaiqi ! I think `modal_aero_lw` also has similar calculations repeated inside it. We can remove those and call this subroutine when we refactor `modal_aero_lw`.

**Comment by tangshuaiqi** [comment]
@singhbalwinder I tried to replace the code in modal_aero_lw with this subroutine but it fails BFB test due to roundoff error (Is it the right error name? I mean something like 1.23456789 vs 1.23456788). I just made a comment there. maybe it can be replaced in C++ porting if they don't need to meet BFB consistency.

**Comment by tangshuaiqi** [comment]
all tests passed. merge into maint

comp_testall_modal_size_parameters_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
