### PR TITLE
Automates E3SM testing for reafactor

### PR DESCRIPTION
**Pull request by singhbalwinder**
This script automates the launch of baseline and comparison runs.
Usage:
1. Go to the root of the E3SM codebase (i.e., e3sm_mam4_refactor directory)
2. Issue command:
           $bash  mam4_refactor_scripts/setup_baselines_and_comparison.sh -t < tag >

3. The command above will launch two separate builds of the E3SM (baseline generation and comparison)
    The tags for the baseline and comparison run will be auto-generated by appending "base_" and "comp_"
   respectively

### CODE REVIEW

**Comment by brigaudet** [comment]
Looks good.  I guess if this script is used to do comparison tests the baseline case will be re-run each time even if not strictly necessary.  If the baseline case fails for whatever reason, it will enter an infinite loop.

**Review by tangshuaiqi — DISMISSED** [review]

**Review by brigaudet — DISMISSED** [review]

**Comment by singhbalwinder** [comment]
Thanks, @brigaudet and @tangshuaiqi! 

@brigaudet: This script is just to set up the baseline and comparison runs for the first time. After they are set, the rest of the workflow remains the same (i.e. change the code, go to the case directory and issue "./case.build && ./case.submit").

I completely agree with you that it may get into an infinite loop if the baseline build/run crashes for some reason. I will add logic to detect that in the script.

**Review by mingxuanwupnnl — APPROVED** [review]

**Comment by singhbalwinder** [comment]
Thanks, guys! I am going to merge this. We will start using this script and modify it to make our workflow more efficient.

**Comment by tangshuaiqi** [comment]
line 29:     scratch_dir="/compyfs/sing201/e3sm_scratch"
should it be     scratch_dir="/compyfs/"$USER"/e3sm_scratch"?

**Pull request merged**
