### PR TITLE
Add YAML/python output for dropmixnuc/maxsat; modify ccncalc output; modify YAML/python output formatting

### PR DESCRIPTION
**Pull request by brigaudet**
1)  Add yaml and python output and generation code for maxsat subroutine within ndrop.F90/dropmixnuc, tagged by parent calling subroutine

2)  Add erroneously excluded 'qcldbrn' to input variables for ccncalc subroutine output and generation code. 

3)  Modify yaml_input_file.io.F90 so scientific notation in yaml/python have three digits in output; otherwise, output of huge() function, used during initialization of some variables, does not print the 'E' in the notation when a particular field in an array still reflects this initialization, interfering with software trying to process the yaml / python files.

### CODE REVIEW

**Review by odiazib — APPROVED** [review]
Looks great!

**Review by jaelynlitz — APPROVED** [review]
In the explmix yaml files, can you change the function name to be explmix instead of compute_tendencies? Otherwise looks great thank you!

**Review by singhbalwinder — APPROVED** [review]
Thanks, Brian for fixing this bug so quickly!

**Comment by brigaudet** [comment]
> 

OK, done!

**Review by jeff-cohere — APPROVED** [review]

**Comment by brigaudet** [comment]
image

All longer tests passed, will merge.

**Pull request merged**
