### PR TITLE
Remove unused code in hetfrz_classnuc_cam.F90

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
Remove unused code for MAM7 and MAM3 in hetfrz_classnuc_cam.F90.

### CODE REVIEW

**Review by singhbalwinder — APPROVED** [review]
Looks good! Thanks, @mingxuanwupnnl !

**Review by tangshuaiqi — APPROVED** [review]

**Comment by brigaudet** [comment]
It looks good to me too!  I just had a comment / general question:  should references to rad_cnst_get_mode_props be retained in the code?  I had removed references to rad_cnst_get_aer_props, but it required the use of some additional array index markers that are defined in the chemistry (modal_aero_data).

**Comment by mingxuanwupnnl** [comment]
@singhbalwinder could you comment on @brigaudet 's question? We probably need to do this in a unified way. Does using index arrays in modal_aero_data work? Or we should do it in another way. Thank you.

**Comment by singhbalwinder** [comment]
Yes, it should be fine to use modal_aero_data.F90 mapping variables to reference the right indices from state%q at this point. C++ data structures are organized a little differently so we may need to revisit it or we can do that on the C++ end only.

**Comment by mingxuanwupnnl** [comment]
@singhbalwinder all tests passed
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel

**Pull request merged**
