### PR TITLE
Adds YAML output generation code using #includes

### PR DESCRIPTION
**Pull request by singhbalwinder**
This PR adds code to generate YAML output for the MMRs (interstitial and cloud borne). The driver code is added using `#includes`.

### CODE REVIEW

**Comment by singhbalwinder** [comment]
I removed the old code in the example.f90 and the output files generated by that code.

**Review by tangshuaiqi — APPROVED** [review]

**Review by jeff-cohere — APPROVED** [review]
Looks good, @singhbalwinder ! I might play around a bit and see whether we can shorten the `.ymlf90` include files so they are less of a burden. Appreciate your work on this.

**Comment by singhbalwinder** [comment]
Thanks, @jeff-cohere! That will be great!

**Comment by singhbalwinder** [comment]
All tests passed:
$ ./cs.status.comp_1yml_mam4_org_v2_baselines -s
comp_1yml_mam4_org_v2_baselines: 5 tests
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel

**Pull request merged**
