### PR TITLE
Generate yaml/python files for tropopause_twmo and dependencies.

### PR DESCRIPTION
**Pull request by brigaudet**
Generate yaml/python files for tropopause_twmo and dependent subroutines twmo and get_dtdz.

Output for the first two are dependent on whole vertical column for some input fields, so those are provided.

### CODE REVIEW

**Review by jeff-cohere — APPROVED** [review]
Looks great. Provisional 👍 from me!

**Review by odiazib — APPROVED** [review]
It looks good to me.

**Review by singhbalwinder — APPROVED** [review]
Looks great!

**Comment by brigaudet** [comment]
image

All longer tests passed, can go ahead and merge.

**Pull request merged**
