### PR TITLE
Adds tests for aerosol drydep and code cleanup

### PR DESCRIPTION
**Pull request by singhbalwinder**
This PR is brining in the following changes:
1. Removal of pbuf,state and cam_in from the aerosol drydep code
2. Removes unused variables
3. Remove non-MAM4 codes
4. Adds tests for some routines
5. Change the precision for printing out the test data to 17  significant digits.

### CODE REVIEW

**Review by tangshuaiqi — APPROVED** [review]
Was surprised by the number of testing files generated. No other comments.

**Comment by singhbalwinder** [comment]
> Was surprised by the number of testing files generated. No other comments.

Yeah, we should probably create another repo for these files.

**Review by jeff-cohere — APPROVED** [review]
That... is a lot of files!

Refactor and cleanup look great!

**Comment by singhbalwinder** [comment]
I will merge it but create a new repo for all the validation data files.

cs.status.comp_tmp_drydep_mam4_org_v2_baselines -s
comp_tmp_drydep_mam4_org_v2_baselines: 9 tests

  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
