### PR TITLE
correct the dimension of state_q in creating YAML files

### PR DESCRIPTION
**Pull request by tangshuaiqi**
correct the wrong dimension of state_q in YAML file or wateruptake
Thanks @mingxuanwupnnl to point out the error.

### CODE REVIEW

**Review by singhbalwinder — APPROVED** [review]
That's a nice catch! We can use `pcnst` here as well.

**Review by mingxuanwupnnl — APPROVED** [review]
looks good to me. I agree that we can also use pcnst.

**Comment by tangshuaiqi** [comment]
I agree that we can use `pcnst` as dimension here, I did not use it because this module does not use `pcnst` at all, so I decided to not adding a new variable.

**Comment by tangshuaiqi** [comment]
All test passed, merge into maint

  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
