### PR TITLE
Add YAML files for subroutines in modal_aero_coag.F90

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
add YAML output for

getcoags
getcoags_wrapper_f
mam_coag_1subarea
mam_coag_aer_update
mam_coag_num_update

### CODE REVIEW

**Review by tangshuaiqi — APPROVED** [review]
It looks good to me. I see that you included two sets of YAML files in different timesteps. Usually we only include multiple sets of input/output files when the subroutine has if/else condition so each set of input/output covers one part of the condition. Since this code does not include multiple conditions, I think you can safely remove one set of input/output files that are not the timestep in your *_beg_yml.f90 file.

**Review by brigaudet — APPROVED** [review]
Looks good to me too.

**Review by pressel — APPROVED** [review]
Thanks, @mingxuanwupnnl!

**Comment by mingxuanwupnnl** [comment]
Removed unnecessary output. All tests passed.

  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
