### PR TITLE
Refactored coagulation up-to-date with refactor-maint-2.0

### PR DESCRIPTION
**Pull request by huiwanpnnl**
This PR replaces PR #32. 

- All comments in the old PR have been addressed. 
- The old branch had a minor conflict with a recent update on `refactor-maint-2.0`, which has been resolved with this new branch.

**Testing on Compy:**

Commands used to run all tests:
```
cd /qfs/people/wanh895/codes/e3sm_mam4_refactor_coag3_merged/
bash mam4_refactor_scripts/compare_baselines_all_tests.sh \
     -b huiwanpnnl/refactor-amicphys-coag3_merged \
     -t coag_refactor_ALL_TESTS
```

Commands used for checking the results:
```
cd /compyfs/wanh895/e3sm_scratch//coag_refactor_ALL_TESTS
./cs.status.comp_coag_refactor_ALL_TESTS_mam4_org_v2_baselines -s
```

The results are
```
comp_coag_refactor_ALL_TESTS_mam4_org_v2_baselines: 5 tests
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
```

### CODE REVIEW

**Review by singhbalwinder — APPROVED** [review]
This looks great! Thanks for addressing all my comments. You moved around codes and data blocks where they belong. It takes time to go into these details and I really appreciate that!

**Comment by singhbalwinder** [comment]
I am going to add more reviewers to know if anybody else has any feedback.

**Review by jeff-cohere — APPROVED** [review]
This is a huge improvement. Thanks, @huiwanpnnl .

**Review by tangshuaiqi — APPROVED** [review]
I quickly looked through the PR and agree that it's a huge work. Just have a minor question that does not affect anything: Is there any reason to change `r8` to `wp`?

**Comment by singhbalwinder** [comment]
> Is there any reason to change `r8` to `wp`?

MAM box model uses `wp` (an alias for "working precision") to support single as well as double precision. `r8` is an alias for double precision. `wp` in these codes is also an alias for double precision.

**Comment by singhbalwinder** [comment]
Merging this PR as all the tests passed.

**Pull request merged**
