### PR TITLE
Adds test suite for mam4 refactor

### PR DESCRIPTION
**Pull request by singhbalwinder**
Adds a test suite to run after the refactor is complete. It includes some important tests to preserve some of the model features such as debug runs, restarts, threading, etc.

### CODE REVIEW

**Comment by singhbalwinder** [comment]
I created this first simple PR to test if everything is setup correctly.

**Review by jeff-cohere — APPROVED** [review]
Looks good to me.

Are you interested in having an automated test setup? Asher arranged something like that with the HPC group(s) at PNNL a while back (though we never completely figured it out). It's possible we could patch Compy into GitHub Actions somehow.

**Comment by singhbalwinder** [comment]
Thanks, @jeff-cohere! Yes, I am looking into that. I may need your help setting it up once I hear back from Compy's support.

**Review by tangshuaiqi — APPROVED** [review]
no problem to me.

will this be run when we do $./create_test *?

**Review by mingxuanwupnnl — APPROVED** [review]

**Comment by singhbalwinder** [comment]
> no problem to me.
> 
> will this be run when we do $./create_test *?

Yes, I will update the instructions after I merge this. This will make it simpler for us to run all the tests in one command after we are done refactoring one subroutine.

**Pull request merged**
