### PR TITLE
clean up mo_jlong.F90 and refactor interpolate_rsf and jlong_photo

### PR DESCRIPTION
**Pull request by tangshuaiqi**
remove unused subroutines and file `mo_waccm_hrates.F90`
separate out a few subroutines
reorganize some code structure to be more readable and consistent.
use subroutine min_max_bound and a few other minor clean ups.

### CODE REVIEW

**Comment by tangshuaiqi** [comment]
add a commit to refactor jlong_photo as well

**Review by jeff-cohere — APPROVED** [review]
Looks good to me. Thanks!

**Review by singhbalwinder — APPROVED** [review]
Looks great! Nice to see repeated code factored out in small subroutines.

**Comment by tangshuaiqi** [comment]
All tests passed. merge into maint

comp_testall_jlong_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
