### PR TITLE
Removes old rename process and deleted unused newnuc codes

### PR DESCRIPTION
**Pull request by singhbalwinder**
Removes old rename code to prepare for moving rename process outside of the amicphys. `modal_aero_gasaerexch.F90` is also removed as it is not used in the current version of the code.

### CODE REVIEW

**Review by tangshuaiqi — APPROVED** [review]

**Review by mingxuanwupnnl — APPROVED** [review]

**Review by jeff-cohere — APPROVED** [review]
👍 

So @singhbalwinder , this version of E3SM is not going to include the nucleation parameterizations at all? Or am I not understanding something?

**Comment by singhbalwinder** [comment]
I just removed the unused codes. The nucleation code is still there but it is the original code that is not refactored.

**Comment by singhbalwinder** [comment]
$ ./cs.status.comp_rem_rename_mam4_org_v2_baselines -s
comp_rem_rename_mam4_org_v2_baselines: 5 tests
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel

**Comment by singhbalwinder** [comment]
All tests passed. I am going to merge this PR as my next PR depends on this PR.

**Pull request merged**
