### PR TITLE
Create YAML file for ndrop.F90/explmix

### PR DESCRIPTION
**Pull request by brigaudet**
1)  Create YAML output for ndrop.F90/explmix subroutine.
2)  Change name of explmix internal variables 'dt' and 'q' to 'dtmix' and 'qnew'.

### CODE REVIEW

**Review by tangshuaiqi — COMMENTED** [review]
Do we need all these yaml files for different `mm` and `actmm `values?

**Comment by brigaudet** [comment]
> Do we need all these yaml files for different `mm` and `actmm `values?

My understanding was that we should have these for each mode and species.  I then assumed we should have these for both activated and unactivated versions of each species, since these are handled through separate subroutine calls.

**Review by singhbalwinder — APPROVED** [review]
Looks good! Would you please add some description about `y_mm`?

**Comment by brigaudet** [comment]
> Looks good! Would you please add some description about `y_mm`?

OK, I've added more annotation for y_mm at the top of  explmix_beg_yml.f90.

**Comment by brigaudet** [comment]
image

All longer tests passed, will go ahead and merge.

**Pull request merged**
