### PR TITLE
refactor imp_sol and all child subroutines

### PR DESCRIPTION
**Pull request by tangshuaiqi**
This PR includes refactor of subroutine imp_sol. All its child subroutines are included as they only need simple cleanups. As suggested by @odiazib , we did regular refactoring on subroutine imp_sol, including remove uncovered code (but still keep the check of inconvergence), separation of small subroutines and some other small clean ups.

### CODE REVIEW

**Review by mjs271 — APPROVED** [review]
Looks good to me. Thank you for breaking some of the larger sections into smaller subroutines--so helpful on our side 🙂

**Review by jeff-cohere — APPROVED** [review]
Thanks, @tangshuaiqi !

**Review by odiazib — APPROVED** [review]

**Review by mingxuanwupnnl — APPROVED** [review]

**Review by singhbalwinder — APPROVED** [review]
Looks great! Thanks, @tangshuaiqi !

**Comment by tangshuaiqi** [comment]
All long-term tests passed, merge this PR

comp_testall_imp_sol_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
