### PR TITLE
Create yaml/python input/output files for dust and sea salt emission subroutines 

### PR DESCRIPTION
**Pull request by mingxuanwupnnl**
create yaml/python input/output for the following subroutines

dust_emis (dust_model.F90)

calculate_seasalt_numflux_in_bins (aero_model.F90)

seasalt_emis (seasalt_model.F90)
marine_organic_emis (seasalt_model.F90)
seasalt_emisflx_calc (seasalt_model.F90)
calc_om_ssa (seasalt_model.F90)
marine_organic_numflx_calc (seasalt_model.F90)
marine_organic_massflx_calc (seasalt_model.F90)

Let me know any new input/output is needed for yaml/py files at this stage.

I'll remove lchnk and comment out YAML_DUST_SSLT_EM conditional compiling flag later.

### CODE REVIEW

**Review by singhbalwinder — APPROVED** [review]
Looks good to me! Thanks!

**Review by tangshuaiqi — APPROVED** [review]
Looks good. Just a reminder to remove the temporary varibles `lchnk`, `y_lchnk` before merging.

**Review by jeff-cohere — APPROVED** [review]
Looks good! Thanks.

**Comment by mingxuanwupnnl** [comment]
All tests passed.
comp_tmp_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Pull request merged**
