### PR TITLE
YAML: fix an index error in convproc

### PR DESCRIPTION
**Pull request by tangshuaiqi**
fix an index problem in yaml testing files for subroutine compute_massflux and compute_ent_det_dp.

### CODE REVIEW

**Comment by singhbalwinder** [comment]
Thanks, @tangshuaiqi for fixing this quickly! 

@overfelt: Would you please use one of these files and test with your ported codes? Thanks!

**Review by singhbalwinder — APPROVED** [review]
Thanks! Let's merge this after running the tests.

**Review by overfelt — APPROVED** [review]

**Comment by tangshuaiqi** [comment]
comp_yaml_convproc_fix_mam4_org_v2_baselines: 9 tests
  PASS ERP_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS ERS.ne4pg2_oQU480.F2010.compy_intel
  PASS PEM_P64x1.ne4pg2_oQU480.F2010.compy_intel
  PASS PET.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P1x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D_Ln5_P32x1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_D.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS_Ly1.ne4pg2_oQU480.F2010.compy_intel
  PASS SMS.ne30pg2_EC30to60E2r2.F2010.compy_intel

**Comment by overfelt** [comment]
@tangshuaiqi , I think the fixes in the pull request "YAML: fix an index error in convproc #116" might need to be extended to ma_convproc_dp_intr_beg_yml.f90 which also output the same arrays of values.  Can you check that?

**Comment by tangshuaiqi** [comment]
@overfelt Sure, I will check and fix it as well.

**Pull request merged**
